### ISSUE TITLE
Not able to find instructions to run the project 

### ISSUE THREAD

**Issue by arpiagariu** [airavata-courses/TeamApex#22]
Hi @airavata-courses/teamapex 

I am not able to find the instructions or Readme File for running the project for completing assignment 3.
Should I use the following file for executing the Milestone-3 :
https://github.com/airavata-courses/TeamApex/blob/master/Science_Gateway_Apex/README.md

Thanks
Arpit

**Comment by vaglomangirish** [comment]
Hi Arpit,

Please use the following Milestone 3 README:-
https://github.com/airavata-courses/TeamApex/wiki/Milestone-3-User-Interface

Thanks.

**Comment by arpiagariu** [comment]
I would like to suggest a UI enhancement in which user can select end system on the forms, instead of changing it in the config file again and again. 

This is a very interesting implementation. :+1:

**Comment by gouravshenoy** [comment]
Thank you for the suggestion @arpiagariu 
These have been incorporated in our implementation.
