### ISSUE TITLE
CI/CD discussion

### ISSUE THREAD

**Issue by ehdsouza** [airavata-courses/TeamApex#30]
Currently we have travis configured to trigger build once a code checking is done. We use this issue, to discuss further on how deployment would be carried out on remote vm.

**Comment by gouravshenoy** [comment]
We considered the following options for CI/CD:
- Jenkins.
- Travis CI

We have decided to go ahead with Travis CI and use Amazon's CodeDeploy service for CD. Travis CI provides easy integration hooks with GitHub for performing automated build. Travis also has a very easy to use integration for deployment using Amazon's CodeDeploy service.
