### ISSUE TITLE
Milestone 6 Issue

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamApex#36]
Appears to work fine but I am not able to create an account or log into http://ec2-52-24-40-94.us-west-2.compute.amazonaws.com:8081/SGA_Apex. 

I'm available through 2 pm today to resolve.

**Comment by vaglomangirish** [comment]
We have delivered the fix.
Thanks for bringing it to our notice. It was a just a simple form input field renaming that needed to be done.
